const request = require('supertest');
const express = require('express');
const fc = require('fast-check');
const jwt = require('jsonwebtoken');
const authRoutes = require('../../src/routes/auth');

// We intentionally bypass express-rate-limit during supertest property tests
// because firing 100 fast-check requests triggers 429 Too Many Requests.
jest.mock('express-rate-limit', () => () => (req, res, next) => next());

require('../../src/middleware/rateLimiter');

// Mock Prisma with in-memory store
jest.mock('../../src/prisma', () => {
  const users = new Map();
  const otps = new Map();

  const mockPrisma = {
    user: {
      findUnique: jest.fn().mockImplementation(async ({ where }) => {
        if (where.email) return users.get(where.email) || null;
        if (where.id) {
          for (let u of users.values()) if (u.id === where.id) return u;
        }
        return null;
      }),
      create: jest.fn().mockImplementation(async ({ data }) => {
        const user = {
          ...data,
          id: Math.random().toString(36).substring(7),
          createdAt: new Date(),
          updatedAt: new Date()
        };
        users.set(data.email, user);
        return user;
      }),
    },
    oTP: {
      create: jest.fn().mockImplementation(async ({ data }) => {
        otps.set(data.email, data);
        return data;
      }),
      findFirst: jest.fn().mockImplementation(async ({ where }) => {
        if (where.email) return otps.get(where.email) || null;
        return null;
      }),
      findUnique: jest.fn().mockImplementation(async ({ where }) => {
        if (where.email) return otps.get(where.email) || null;
        return null;
      }),
      deleteMany: jest.fn().mockImplementation(async ({ where }) => {
        if (where.email) otps.delete(where.email);
        return { count: 0 };
      }),
      delete: jest.fn().mockImplementation(async ({ where }) => {
        if (where.email) {
          const val = otps.get(where.email);
          otps.delete(where.email);
          return val;
        }
        return null;
      }),
      upsert: jest.fn().mockImplementation(async ({ where, update, create }) => {
        if (otps.has(where.email)) {
          otps.set(where.email, { ...otps.get(where.email), ...update });
        } else {
          otps.set(where.email, create);
        }
        return otps.get(where.email);
      }),
    },
    $disconnect: jest.fn(),
  };

  mockPrisma.$transaction = jest.fn().mockImplementation(async (callback) => {
    return await callback(mockPrisma);
  });

  return mockPrisma;
});

const prisma = require('../../src/prisma');
const hashOTP = require('../../src/utils/hashOTP');

jest.mock('../../src/services/emailService', () => ({
  sendOTPEmail: jest.fn().mockResolvedValue(true)
}));

/**
 * Property-Based Tests for Auth Routes
 * Feature: auth-integration
 */

// Create express app for testing
const app = express();
app.use(express.json());
app.use('/auth', authRoutes);

describe('Auth Routes - Property-Based Tests', () => {
  beforeAll(() => {
    process.env.JWT_SECRET = 'test-secret-key-for-property-tests';
  });

  afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * Property 3: Authentication API returns valid response structure
   */
  it('Property 3: Authentication API returns valid response structure', async () => {
    await fc.assert(
      fc.asyncProperty(
        // Generate random email addresses
        fc.emailAddress().map(email => {
          const timestamp = Date.now();
          const random = Math.random().toString(36).substring(7);
          return `${email.split('@')[0]}-${timestamp}-${random}@property-test.com`;
        }),
        async (email) => {

          // Request an OTP
          const requestOtpResponse = await request(app)
            .post('/auth/request-otp')
            .send({ email });

          if (requestOtpResponse.statusCode !== 200) {
            console.error('requestOtp error:', requestOtpResponse.body);
          }
          expect(requestOtpResponse.statusCode).toBe(200);

          // Get the OTP hash from the stubbed DB
          const otpRecord = await prisma.oTP.findFirst({ where: { email } });
          expect(otpRecord).toBeDefined();

          // We don't have the plain OTP generated by the server because it's mocked in sendEmail.
          // To test verify-otp structurally via property, we manually plant a known OTP in our memory map.
          const knownOtp = '123456';
          await prisma.oTP.create({
            data: {
              email: email,
              otpHash: hashOTP(knownOtp),
              expiresAt: new Date(Date.now() + 5 * 60 * 1000)
            }
          });

          // Test verification endpoint response structure
          const verifyResponse = await request(app)
            .post('/auth/verify-otp')
            .send({
              email: email,
              otp: knownOtp
            });

          // Status should be 200
          expect(verifyResponse.statusCode).toBe(200);

          // Response should have a token field (string)
          expect(verifyResponse.body).toHaveProperty('token');
          expect(typeof verifyResponse.body.token).toBe('string');
          expect(verifyResponse.body.token.length).toBeGreaterThan(0);

          // Response should have a user object
          expect(verifyResponse.body).toHaveProperty('user');
          expect(typeof verifyResponse.body.user).toBe('object');
          expect(verifyResponse.body.user).not.toBeNull();

          // User object should have id, email, role fields
          expect(verifyResponse.body.user).toHaveProperty('id');
          expect(typeof verifyResponse.body.user.id).toBe('string');
          expect(verifyResponse.body.user.id.length).toBeGreaterThan(0);

          expect(verifyResponse.body.user).toHaveProperty('email');
          expect(verifyResponse.body.user.email).toBe(email);

          expect(verifyResponse.body.user).toHaveProperty('role');
        }
      ),
      { numRuns: 10 }
    );
  }, 60000);
});
